services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fcmb_sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperSecureP@ssw0rd2026!
    ports:
      - "1433:1433"
    healthcheck:
      # Pings the server repeatedly to ensure it is actually accepting connections
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SuperSecureP@ssw0rd2026!", "-C", "-Q", "SELECT 1" ]
      interval: 5s
      timeout: 5s
      retries: 10

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fcmb_db_init
    depends_on:
      sqlserver:
        condition: service_healthy # Waits for the healthcheck above to pass
    volumes:
      - ./init.sql:/init.sql
    # Connects to the 'sqlserver' service and executes the script
    command: /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P "SuperSecureP@ssw0rd2026!" -C -i /init.sql
